services:

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "yashmorbita/configserver:s2"
    container_name: configserver-ms
    ports:
      - "8071:8080"
    depends_on:
      rabbit:
        condition: service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "yashmorbita/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "yashmorbita/loans:s2"
    container_name: loans-ms
    ports:
      - "8090:8080"
    environment:
      SPRING_APPLICATION_NAME: "laons"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  cards:
    image: "yashmorbita/cards:s2"
    container_name: cards-ms
    ports:
      - "9000:8080"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"

