server:
  port: 9010
spring:
  application:
    name: "message"
  cloud:
    function:
      definition: sendEmail|sendSms
    stream:
      bindings:
        sendEmailsendSms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        sendEmailsendSms-out-0:
          destination: communication-sent
        kafka:
          binder:
            brokers:
              - localhost:9092
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s



